// Portfolio releases — generated from the cover images by scripts/build-covers.mjs.
// Each entry: a real OddWave release. Fill `spotify` with the track/album URL
// (or run the Spotify search step). `art` is the gradient fallback.
import type { SynthCover } from './portfolioSynth';

export const RELEASES: readonly SynthCover[] = [
  { title: "13390", artist: "AFTER THE RAIN", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#7C5B3A,#33241A)", image: "/assets/cover/after-the-rain-13390.jpg", spotify: '' },
  { title: "LE MIEL DES ANGES", artist: "ALCAZ", tag: "Prod & Mix", type: "Album", art: "linear-gradient(145deg,#2A2D34,#14151A)", image: "/assets/cover/alcaz-le-miel-des-anges.jpg", spotify: '' },
  { title: "PORTES PAR LES VENTS", artist: "ALCAZ", tag: "Real Prod & Mix", type: "Album", art: "linear-gradient(145deg,#1E3A44,#101D22)", image: "/assets/cover/alcaz-portes-par-les-vents.jpg", spotify: '' },
  { title: "HAATHEE", artist: "AMAJEE", tag: "Mastering", type: "Single", art: "linear-gradient(145deg,#7C5B3A,#33241A)", image: "/assets/cover/amajee-haathee.jpg", spotify: '' },
  { title: "TRANSIENCE", artist: "AROKEM", tag: "Mastering", type: "Ep", art: "linear-gradient(145deg,#52384E,#1E1420)", image: "/assets/cover/arokem-transience.jpg", spotify: '' },
  { title: "FIREDROP", artist: "ASHKABAD", tag: "Mix & Mastering", type: "Album", art: "linear-gradient(145deg,#4A4E57,#1C1E24)", image: "/assets/cover/ashkabad-firedrop.jpg", spotify: '' },
  { title: "FIRESTICK", artist: "BANDI!", tag: "Stem Mastering", type: "Album", art: "linear-gradient(145deg,#33363E,#16171C)", image: "/assets/cover/bandi-firestick.jpg", spotify: '' },
  { title: "GALACTIC ANTHEM", artist: "BASS TROOPERZ", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#A8443A,#3A1714)", image: "/assets/cover/bass-trooperz-galactic-anthem.jpg", spotify: '' },
  { title: "CHAPTER 20", artist: "BONNIE SPACEY", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#7C5B3A,#33241A)", image: "/assets/cover/bonnie-spacey-chapter-20.jpg", spotify: '' },
  { title: "DANCING IN THE RAIN", artist: "BONNIE SPACEY", tag: "Mix & Mastering", type: "Single", art: "linear-gradient(145deg,#2A2D34,#14151A)", image: "/assets/cover/bonnie-spacey-dancing-in-the-rain.jpg", spotify: '' },
  { title: "MURUNNA", artist: "CAPTAIN PASTEK", tag: "Mastering", type: "Ep", art: "linear-gradient(145deg,#C24E37,#5E2218)", image: "/assets/cover/captain-pastek-murunna.jpg", spotify: '' },
  { title: "SUN SEAKER", artist: "DRIBBLE", tag: "Mastering", type: "Album", art: "linear-gradient(145deg,#A8443A,#3A1714)", image: "/assets/cover/dribble-sun-seaker.jpg", spotify: '' },
  { title: "IT'S BEEN A WHILE", artist: "EARTHWORM & NINESENS", tag: "Mix & Mastering", type: "Single", art: "linear-gradient(145deg,#244640,#0F1D1A)", image: "/assets/cover/earthworm-ninesens-it-s-been-a-while.jpg", spotify: '' },
  { title: "DRIFT", artist: "EX-ECHO", tag: "Stem Mastering", type: "Ep", art: "linear-gradient(145deg,#2A2D34,#14151A)", image: "/assets/cover/ex-echo-drift.jpg", spotify: '' },
  { title: "COMPILATION", artist: "FRENCH KISS", tag: "Mastering", type: "Mastering", art: "linear-gradient(145deg,#3A2E4A,#16121E)", image: "/assets/cover/french-kiss-compilation.jpg", spotify: '' },
  { title: "LOCKED IN PARADISE", artist: "HALFORM", tag: "Stem Mastering", type: "Album", art: "linear-gradient(145deg,#52384E,#1E1420)", image: "/assets/cover/halform-locked-in-paradise.jpg", spotify: '' },
  { title: "DUN & SARK", artist: "L'ART CENE", tag: "Mix & Mastering", type: "Album", art: "linear-gradient(145deg,#1E3A44,#101D22)", image: "/assets/cover/l-art-cene-dun-sark.jpg", spotify: '' },
  { title: "RAINBOW MACHINE", artist: "MAHOM", tag: "Mix & Mastering", type: "Album", art: "linear-gradient(145deg,#C2683A,#4A2414)", image: "/assets/cover/mahom-rainbow-machine.jpg", spotify: '' },
  { title: "ON MY WAY", artist: "MOJO JULES & BREWBUD", tag: "Mastering", type: "Ep", art: "linear-gradient(145deg,#3A2E4A,#16121E)", image: "/assets/cover/mojo-jules-brewbud-on-my-way.jpg", spotify: '' },
  { title: "NOVUS DISCO SECLORUM", artist: "NEW FUNK ORDER", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#6E4A2E,#2A1B11)", image: "/assets/cover/new-funk-order-novus-disco-seclorum.jpg", spotify: '' },
  { title: "MIND BENDING", artist: "OPTICAL MIND GATE", tag: "Mastering", type: "Ep", art: "linear-gradient(145deg,#244640,#0F1D1A)", image: "/assets/cover/optical-mind-gate-mind-bending.jpg", spotify: '' },
  { title: "SHOW ME EVERITHING", artist: "OPTICAL MIND GATE", tag: "Mastering", type: "Ep", art: "linear-gradient(145deg,#6E4A2E,#2A1B11)", image: "/assets/cover/optical-mind-gate-show-me-everithing.jpg", spotify: '' },
  { title: "MOODZ TRACKER", artist: "RADIKAL MOODZ", tag: "Mastering", type: "Ep", art: "linear-gradient(145deg,#244640,#0F1D1A)", image: "/assets/cover/radikal-moodz-moodz-tracker.jpg", spotify: '' },
  { title: "SERENDIPITY", artist: "RAKOON", tag: "Mix", type: "Album", art: "linear-gradient(145deg,#2A2D34,#14151A)", image: "/assets/cover/rakoon-serendipity.jpg", spotify: '' },
  { title: "SOMETHING PRECIOUS", artist: "RAKOON", tag: "Mix", type: "Album", art: "linear-gradient(145deg,#3A2E4A,#16121E)", image: "/assets/cover/rakoon-something-precious.jpg", spotify: '' },
  { title: "THE ONES WE LOVE", artist: "RAKOON", tag: "Mix", type: "Ep", art: "linear-gradient(145deg,#A8443A,#3A1714)", image: "/assets/cover/rakoon-the-ones-we-love.jpg", spotify: '' },
  { title: "CELLULAR MECHANICS", artist: "SHRED'ER", tag: "Stem Mastering", type: "Album", art: "linear-gradient(145deg,#C24E37,#5E2218)", image: "/assets/cover/shred-er-cellular-mechanics.jpg", spotify: '' },
  { title: "EGG DEALER", artist: "SILOKA", tag: "Stem Mastering", type: "Ep", art: "linear-gradient(145deg,#4A4E57,#1C1E24)", image: "/assets/cover/siloka-egg-dealer.jpg", spotify: '' },
  { title: "NONSENS", artist: "SILOKA", tag: "Stem Mastering", type: "Album", art: "linear-gradient(145deg,#52384E,#1E1420)", image: "/assets/cover/siloka-nonsens.jpg", spotify: '' },
  { title: "STR001", artist: "SLEEPING TRACKS RECORDS", tag: "Mastering", type: "Compilation", art: "linear-gradient(145deg,#A8443A,#3A1714)", image: "/assets/cover/sleeping-tracks-records-str001.jpg", spotify: '' },
  { title: "STR002", artist: "SLEEPING TRACKS RECORDS", tag: "Mastering", type: "Compilation", art: "linear-gradient(145deg,#33363E,#16171C)", image: "/assets/cover/sleeping-tracks-records-str002.jpg", spotify: '' },
  { title: "STR003", artist: "SLEEPING TRACKS RECORDS", tag: "Mastering", type: "Compilation", art: "linear-gradient(145deg,#2A2D34,#14151A)", image: "/assets/cover/sleeping-tracks-records-str003.jpg", spotify: '' },
  { title: "STR005", artist: "SLEEPING TRACKS RECORDS", tag: "Mastering", type: "Compilation", art: "linear-gradient(145deg,#3A2E4A,#16121E)", image: "/assets/cover/sleeping-tracks-records-str005.jpg", spotify: '' },
  { title: "STR006", artist: "SLEEPING TRACKS RECORDS", tag: "Mastering", type: "Compilation", art: "linear-gradient(145deg,#C2683A,#4A2414)", image: "/assets/cover/sleeping-tracks-records-str006.jpg", spotify: '' },
  { title: "RUST", artist: "SLIP HYPNOTIC", tag: "Stem Mastering", type: "Album", art: "linear-gradient(145deg,#C2683A,#4A2414)", image: "/assets/cover/slip-hypnotic-rust.jpg", spotify: '' },
  { title: "PRISM", artist: "SMOOTH CRIMINAL", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#33363E,#16171C)", image: "/assets/cover/smooth-criminal-prism.jpg", spotify: '' },
  { title: "THE THING", artist: "SMOOTH CRIMINAL", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#6E4A2E,#2A1B11)", image: "/assets/cover/smooth-criminal-the-thing.jpg", spotify: '' },
  { title: "BAD OMEN", artist: "SMOOTH CRIMINAL & DIFAZ", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#4A4E57,#1C1E24)", image: "/assets/cover/smooth-criminal-difaz-bad-omen.jpg", spotify: '' },
  { title: "REVOLT FM", artist: "SOMBRRR", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#7C5B3A,#33241A)", image: "/assets/cover/sombrrr-revolt-fm.jpg", spotify: '' },
  { title: "LYRAE", artist: "SUMAC", tag: "Mix", type: "Album", art: "linear-gradient(145deg,#C24E37,#5E2218)", image: "/assets/cover/sumac-lyrae.jpg", spotify: '' },
  { title: "ARAMBOL", artist: "TAALKIMIA", tag: "Mix & Mastering", type: "Single", art: "linear-gradient(145deg,#7C5B3A,#33241A)", image: "/assets/cover/taalkimia-arambol.jpg", spotify: '' },
  { title: "BIOHACKERS", artist: "THE HORRIDS", tag: "Stem Mastering", type: "Album", art: "linear-gradient(145deg,#1E3A44,#101D22)", image: "/assets/cover/the-horrids-biohackers.jpg", spotify: '' },
  { title: "ODYSSEE", artist: "THK", tag: "Mastering", type: "Album", art: "linear-gradient(145deg,#1E3A44,#101D22)", image: "/assets/cover/thk-odyssee.jpg", spotify: '' },
  { title: "SMOKING SESSIONS", artist: "THK", tag: "Mastering", type: "Album", art: "linear-gradient(145deg,#52384E,#1E1420)", image: "/assets/cover/thk-smoking-sessions.jpg", spotify: '' },
  { title: "THK & BAKU & JAEL", artist: "THK & BAKU & JAEL", tag: "Mastering", type: "Album", art: "linear-gradient(145deg,#244640,#0F1D1A)", image: "/assets/cover/thk-baku-jael-thk-baku-jael.jpg", spotify: '' },
  { title: "BACK TO THE START", artist: "TOM BAKER", tag: "Mastering", type: "Single", art: "linear-gradient(145deg,#C24E37,#5E2218)", image: "/assets/cover/tom-baker-back-to-the-start.jpg", spotify: '' },
  { title: "SHIVERS", artist: "TOM BAKER", tag: "Mastering", type: "Single", art: "linear-gradient(145deg,#C24E37,#5E2218)", image: "/assets/cover/tom-baker-shivers.jpg", spotify: '' },
  { title: "CYCLE DES MIROIRS", artist: "VENT DES FORETS", tag: "Stem Mastering", type: "Ep", art: "linear-gradient(145deg,#33363E,#16171C)", image: "/assets/cover/vent-des-forets-cycle-des-miroirs.jpg", spotify: '' },
  { title: "LA SOURCE", artist: "VENT DES FORETS", tag: "Stem Mastering", type: "Ep", art: "linear-gradient(145deg,#4A4E57,#1C1E24)", image: "/assets/cover/vent-des-forets-la-source.jpg", spotify: '' },
  { title: "CACTUS & CARTOUCHES", artist: "WILOKAT", tag: "Mix & Mastering", type: "Ep", art: "linear-gradient(145deg,#6E4A2E,#2A1B11)", image: "/assets/cover/wilokat-cactus-cartouches.jpg", spotify: '' },
  { title: "DAUGHTER", artist: "WIZA WITCH", tag: "Mix & Mastering", type: "Album", art: "linear-gradient(145deg,#C2683A,#4A2414)", image: "/assets/cover/wiza-witch-daughter.jpg", spotify: '' },
];
